server:
  port: 8000

#logging.level.com.smockin: ERROR

jpa:
  show-sql: false
  hibernate:
    ddl-auto: create-drop
datasource:
  url: jdbc:h2:mem:smockindev
  driver-class-name: org.h2.Driver
  username: sa
  password:

smockin:
  auth.exclusions: '{"*.html":["GET"],"*.js":["GET"],"*.css":["GET"],"*.woff2":["GET"],"*.png":["GET"],"*.gif":["GET"],"*.ico":["GET"],"/auth":["POST"],"/user/mode":["GET"],"/mockedserver/rest/status":["GET"],"/mockedserver/jms/status":["GET"],"/mockedserver/ftp/status":["GET"],"/password/reset/token/*":["GET","POST"]}'

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20971520 #20 MB
      max-request-size: 20971520 #20 MB

---
# NOTE
# The 'start.sh' script overrides the below DB related params using values defined
# in the DB config file: '$USER_HOME/.smockin/db/db.properties'.
spring:
  profiles:
    active: production
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url:
    driver-class-name:
    username:
    password:
    maximumPoolSize: 10
    hikari:
      poolName: smockinpool
      idle-timeout: 10000